create database house;

USE HOUSE;

CREATE TABLE RESIDENTS(
ID INT PRIMARY KEY,
NAME VARCHAR(50), 
RENT INT
);

SHOW TABLES;

INSERT INTO RESIDENTS VALUES(1, "NIKHIL", 1500);
INSERT INTO RESIDENTS VALUES(2, "SHWETA", 500);
INSERT INTO RESIDENTS VALUES(3, "RONIT", 500);
